name: Escalade Deploy Alpha

env:
  module_app: app

on:
  push:
    branches:
      - "main"
    tags:
       - "*"
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0 #To Fetch All Tags and Branches

    - name: Install Dependencies
      uses: php-actions/composer@v6
      with:
        dev: no

    ##########################################
    # Push / Pull translation files          #
    ##########################################
    # Push Transifex
    - name: Push source file using transifex client
      uses: transifex/cli-action@v2
      with:
        args: push
        token: ${{ secrets.TX_TOKEN }}

    # Clean Transifex CLI
    - name: Clean Transifex CLI
      run: rm -fr /tmp/tx

    # Pull from Transifex
    - name: Pull source file using transifex client
      uses: transifex/cli-action@v2
      with:
        args: pull
        token: ${{ secrets.TX_TOKEN }}